### ISSUE TITLE
servlet-api dependency should not be transitive

### ISSUE THREAD

**Issue by kelseyfrancis** [gtri/typesafeconfig-extensions#5]

**Comment by chris-martin** [comment]
I realize that the Servlet API is the canonical example of a `provided` dependency ...

> [...] when building a web application for the Java Enterprise Edition, you would set the dependency on the Servlet API and related Java EE APIs to scope provided because the web container provides those classes.
> 
> https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

... but in this case, `for-webapps` could conceivably be used in a web application that doesn't involve the Servlet API. So I think it should actually be an `optional` dependency.

Now I'm trying to figure out: Is there actually any difference between `<scope>provided</scope>` and `<optional>true</optional>`? In both cases, the dependency is not transitive and is available at compile time.
